MMT-3302: As a user, I can view the UMM-T preview in MMT
nasa/mmt pull request #1019
Opened 2023-06-09 17:08 UTC by dmistry1

2023-06-09 19:57 UTC, htranho approved these changes

2023-06-09 19:58 UTC, htranho requested changes
merge to branch?

2023-06-09 20:00 UTC, cgokey approved these changes

2023-06-09 20:01 UTC, cgokey requested changes
Yeah maybe this should go to a integration branch

2023-06-09 21:34 UTC, htranho approved these changes

2023-06-13 17:38 UTC, tle1989 approved these changes

2023-06-13 20:01 UTC, cgokey commented on app/javascript/components/editor/App.tsx
> +          <Route path={`/${editor.model.documentType}/draftDeletedView`} element={<DeleteDraftView editor={editor} {...this.props} />} />
maybe make this endpoint the same for consistency, deleteDraftView

2023-06-15 14:40 UTC, cgokey approved these changes

2023-06-15 14:59 UTC, merged