Mmt 3531
nasa/mmt pull request #1224
Opened 2024-06-03 20:48 UTC by dmistry1

# Overview

### What is the feature?

Please summarize the feature or fix.

### What is the Solution?

Summarize what you changed.

### What areas of the application does this impact?

List impacted areas.

# Testing

### Reproduction steps

- **Environment for testing:**
- **Collection to test with:**

1. Step 1
2. Step 2...

### Attachments

Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-06-06 15:37 UTC, dmistry1 commented on static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx
> +      await waitForResponse()
Remove this

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +import './CollectionSelector.scss'
scss imports should be last, lodash-es import should be at the top with other 3rd party libraries

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +      (item) => !selected.some((s) => s.conceptId === item.conceptId)
Don't use single letter variable names (throughout this file). Using descriptive variable names makes the code easier to read and understand.

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
> +    <AuthContext.Provider value={
Is AuthContext being used in the component?

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
> +      await user.click(nameField)
I'm confused why there are 3 clicks here, selecting and unselecting is only two actions. 

It is a good idea to perform an assertion on something after user actions, especially if the user action is the same each time

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
> +      expect(screen.getByText('Showing 1 items')).toBeInTheDocument()
If this is a result of a network request happening after the user types, it might need to be `expect(await screen.findByText(....`

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
> +      expect(await screen.findByText('Collection 2 | Collection 2 title')).toBeInTheDocument()
only the first expect after the action needs to use await and findBy

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomCheckboxWidget/CustomCheckboxWidget.jsx
> +const CustomCheckboxWidget = ({
Also sort the props

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomCheckboxWidget/CustomCheckboxWidget.jsx
> +
Remove empty line

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomCheckboxWidget/__tests__/CustomCheckboxWidget.test.jsx
> +    user: userEvent.setup()
Define `user` before `render`

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomCheckboxWidget/__tests__/CustomCheckboxWidget.test.jsx
> +    vi.importActual('../../CustomWidgetWrapper/CustomWidgetWrapper').default
If every test needs the actual CustomWidgetWrapper then include this in the `vi.mock()` call. But you also aren't doing any assertions on CustomWidgetWrapper, so do you even need to mock it at all?

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomDateTimeWidget/CustomDateTimeWidget.jsx
> +  disabled,
Update the jsdoc comment

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/CustomFieldTemplate/CustomFieldTemplate.jsx
> +  disabled,
Update the jsdoc comment

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/GroupPermissionSelect/GroupPermissionSelect.jsx
> +import { debounce } from 'lodash-es'
Move 3rd party library imports above our code imports

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/GroupPermissionSelect/__tests__/GroupPermissionSelect.test.jsx
> +    <AuthContext.Provider value={
Is this being used?

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/GroupPermissionSelect/__tests__/GroupPermissionSelect.test.jsx
> +      expect(await screen.findByText('All registered user')).toBeInTheDocument()
Should only need await findBy on the first query after an action

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +import { useNavigate, useParams } from 'react-router'
Move 3rd part imports

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +  const collectionMinValue = formData.accessConstraintFilter
Destructure these values, avoid chains of multiple calls into nested objects and avoid repeated code.

It is difficult to follow this logic, adding comments on each check about what it is actually validating might be useful.

I think this function should also be pulled out into a util and unit tested there

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +const PermissionForm = () => {
Jsdoc comment

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +  const showGranuleFields = (formData) => {
Add comments explaining logic

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +  useEffect(() => {
This useEffect is 149 lines long with no comments explaining anything ;) Describe the purpose of the useEffect, and comment logic throughout

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +        collectionIdentifier,
Sorting these lines makes them easier to read. Any time you are dealing with an object, destructuring or writing, sort the lines to make it easier to read and maintain

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +      groupPermissions
Sort

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +        name,
Sort

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +  const handleSubmit = () => {
This is another massive function with no comments. For these large functions, look for ways to pull logic out into smaller chunks that are easier to understand

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionForm/PermissionForm.jsx
> +      collectionApplicable,
Sort

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionFormPage/PermissionFormPage.jsx
> +const PermissionFormPageHeader = () => {
jsdoc

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionFormPage/PermissionFormPage.jsx
This Page component should be in the Pages directory

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionFormPage/__tests__/PermissionFormPage.test.jsx
> +    <Providers>
Does this actually need Providers?

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionFormPage/__tests__/PermissionFormPage.test.jsx
> +      expect(await screen.findByText('Collection Permission')).toBeInTheDocument()
The await findBy should happen first after the action

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionFormPage/__tests__/PermissionFormPage.test.jsx
> +    user
You aren't using this anywhere in the test

2024-06-07 17:55 UTC, macrouch commented on static/src/js/components/PermissionList/PermissionList.jsx
> +  const buildActionsCell = useCallback((cellData, rowData) => {
This useCallback needs a dependency array

2024-06-07 17:55 UTC, macrouch commented on static/src/js/operations/queries/getCollectionPermission.js
> +   query GetCollectionPermission($conceptId: String!, $collectionParams: CollectionsInput) {
These indentation changes should be removed

2024-06-07 17:55 UTC, macrouch commented on static/src/js/operations/queries/getGroupsForPermissionSelect.js
> +  query Groups (
Update this name to match filename

2024-06-07 17:55 UTC, macrouch commented on static/src/js/pages/CollectionSelectorPage/CollectionSelectorPage.jsx
> +} from 'react-bootstrap'
Wrong bootstrap imports

2024-06-07 17:55 UTC, macrouch commented on static/src/js/pages/PermissionListPage/__tests__/PermissionListPage.test.jsx
> +import { BrowserRouter } from 'react-router-dom'
MemoryRouter

2024-06-07 17:55 UTC, macrouch commented on static/src/js/pages/PermissionPage/PermissionPage.jsx
> +import { FaEdit } from 'react-icons/fa'
Move import

2024-06-07 17:55 UTC, macrouch commented on static/src/js/pages/PermissionListPage/PermissionListPage.jsx
> +import { FaPlus } from 'react-icons/fa'
Move import

2024-06-10 15:38 UTC, dmistry1 commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +                        aria-hidden="true"
This can be removed, I added it when I was testing but it is not needed

2024-06-11 18:55 UTC, trevorlang commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +                                'collection-selector__list-group-item-secondary': selected.some(
I think the primary and secondary classes here should be written as modifiers of the base `collection-selector__list-group-item` and not as elements. Take a look at the BEM methodology documentation. Happy to help if you need clarification.

2024-06-11 18:55 UTC, trevorlang commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +                                'collection-selector__list-group-item-primary': selectedSelected.some(
Same comment as above

2024-06-11 18:55 UTC, trevorlang commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +                          //   ClassName={
Remove commented code

2024-06-11 18:55 UTC, trevorlang commented on static/src/js/components/PermissionList/PermissionList.jsx
> +import { FaEdit } from 'react-icons/fa'
This should be with the other library component imports

2024-06-12 11:46 UTC, trevorlang requested changes

2024-06-12 11:46 UTC, trevorlang commented on static/src/js/components/CollectionSelector/CollectionSelector.scss
> +  &__list-group-item-selected {
Last thing. These modifier classes should be written like `--is-selected` or `--is-available`.

You can do something like this with the scss:

```css
&__list-group-item {
    ...

    &--is-selected {
        ...
    }
    
    &--is-available {
        ...
    }
}
```

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +   * Moves items from `selectedAvailable` to `selectedItems`.
selectedAvailable -> highlightedAvailable

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +   * from the `selected` column and adds them back to the `availableItems` column.
selected -> selectedItems

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +    // SetAvailable(newAvailable)
Remove

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +  const [selectedItems, setSelected] = useState({})
setSelected -> setSelectedItems

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +    setSelected({})
setSelectedItems

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +   * This function clears all selected states (`selected`, `selectedAvailable`, and `highlightedSelected`)
selected -> selectedItems
selectedAvailable -> highlightedAvailable

2024-06-12 15:14 UTC, macrouch commented on static/src/js/components/CollectionSelector/CollectionSelector.jsx
> +    const inputValue = value
This line is unnecessary, just use the `value` variable in the next lines

2024-06-12 17:23 UTC, macrouch approved these changes

2024-06-12 19:11 UTC, trevorlang approved these changes

2024-06-12 19:13 UTC, merged