MMT-1894: Fix "Subtype Not Provided" in CMR data information page download tab
nasa/mmt pull request #672
Opened 2020-12-01 13:49 UTC by ChristianTrummer99

- the default flow for URLs that do not have a Subtype or Type is Subtype > Type > 'Download Data'
- Tests

2020-12-01 15:41 UTC, charleshuang80 commented on spec/features/collection_previews/download_data_tab_preview_spec.rb
> +    context 'when there is metadata but Subtype was not supplied' do
same comment as in preview gem PR

2020-12-02 13:56 UTC, ryanmiller-1 commented on spec/features/collection_drafts/forms/required_fields_spec.rb
> +        expect(page).to have_css('label.eui-required-o', count: 29)
Since you're making a change here, it might be nice to document what the 29 expected required icons are coming from (generally) in a comment.

2020-12-02 13:57 UTC, ryanmiller-1 commented on spec/features/collection_previews/download_data_tab_preview_spec.rb
> +      it 'display metadata' do
If you change anything else, grammar here.

2020-12-03 00:31 UTC, william-valencia commented on Gemfile
> +gem 'cmr_metadata_preview', git: 'https://git.earthdata.nasa.gov/scm/cmr/cmr_metadata_preview.git', branch: 'MMT-1894'#ref: '07fb716bbc0e4b74a6546895fa61ef1fef2614f4'
These changes should not be committed.

2020-12-03 00:31 UTC, william-valencia commented on Gemfile.lock
> +  revision: 37bd439cc48a4b3857f7bbf6c420cd2613bcb8a2
These changes should not be committed.

2020-12-03 16:38 UTC, ryanmiller-1 approved these changes

2020-12-03 16:40 UTC, ryanmiller-1 requested changes
Commit ID does not match current master in preview gem

2020-12-03 17:43 UTC, ryanmiller-1 approved these changes

2020-12-03 21:50 UTC, william-valencia approved these changes

2020-12-04 13:49 UTC, merged