Mmt 2823
nasa/mmt pull request #821
Opened 2022-03-08 16:23 UTC by bademiluyi

Fix tests failures.

2022-03-09 15:37 UTC, bademiluyi commented
Updated. Ready for review.

2022-03-09 15:43 UTC, cgokey commented on spec/features/collection_drafts/publish_collection_draft_spec.rb
> +          #find('label.tab-label', text: 'Citation Information').click
remove this

2022-03-09 16:31 UTC, cgokey approved these changes

2022-03-09 16:47 UTC, tle1989 approved these changes

2022-03-09 21:54 UTC, cgokey requested changes
Still seeing the =>

2022-03-09 21:54 UTC, cgokey commented on spec/features/collection_drafts/auto_populate_metadata_dates_spec.rb
> +      within '#metadata-preview' do
This still needs to be fixed.

2022-03-09 21:54 UTC, cgokey commented on spec/features/collection_drafts/auto_populate_metadata_dates_spec.rb
> +        expect(page).to have_content('"MetadataDates"=>[{"Type"=>"CREATE", "Date"=>"')
Change the =>

2022-03-10 15:02 UTC, cgokey approved these changes

2022-03-10 15:02 UTC, merged